name: catdex
description: CatDex mobile game foundation.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.3.1
  flutter_map_marker_cluster: ^8.2.2
  flutter_riverpod: ^3.0.0
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  go_router: ^16.0.0
  google_mobile_ads: ^9.0.0
  image: ^4.5.4
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.15.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  test: ^1.26.0
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cards/templates/common_card_template.png
    - assets/cards/test_illustrated_cat.png
