import 'package:catdex/features/achievements/domain/achievement_models.dart';

abstract final class AchievementCatalogV1 {
  static const halloweenEventKey = 'halloween_2026';
  static const halloweenFreeVariants = {
    'halloween_pumpkins',
    'halloween_moonlight',
    'halloween_haunted_frame',
  };
  static const halloweenPremiumVariants = {
    'halloween_witch_cat',
    'halloween_pumpkin_king',
    'halloween_night_spirit',
  };

  static const definitions = <AchievementDefinition>[
    _Definition(
      'first_discovery',
      AchievementCategory.discoveries,
      AchievementMetric.persistedDiscoveries,
      1,
      50,
      1,
      AchievementTier.bronze,
      'paw',
    ),
    _Definition(
      'discovery_5',
      AchievementCategory.discoveries,
      AchievementMetric.persistedDiscoveries,
      5,
      100,
      2,
      AchievementTier.bronze,
      'compass',
    ),
    _Definition(
      'discovery_10',
      AchievementCategory.discoveries,
      AchievementMetric.persistedDiscoveries,
      10,
      150,
      3,
      AchievementTier.silver,
      'eye',
    ),
    _Definition(
      'discovery_25',
      AchievementCategory.discoveries,
      AchievementMetric.persistedDiscoveries,
      25,
      300,
      4,
      AchievementTier.gold,
      'map',
    ),
    _Definition(
      'discovery_50',
      AchievementCategory.discoveries,
      AchievementMetric.persistedDiscoveries,
      50,
      500,
      5,
      AchievementTier.gold,
      'binoculars',
    ),
    _Definition(
      'discovery_100',
      AchievementCategory.discoveries,
      AchievementMetric.persistedDiscoveries,
      100,
      1000,
      6,
      AchievementTier.platinum,
      'crown',
    ),
    _Definition(
      'first_normal_card',
      AchievementCategory.cards,
      AchievementMetric.persistedNormalCards,
      1,
      75,
      7,
      AchievementTier.bronze,
      'card',
    ),
    _Definition(
      'normal_cards_10',
      AchievementCategory.cards,
      AchievementMetric.persistedNormalCards,
      10,
      200,
      8,
      AchievementTier.silver,
      'cards',
    ),
    _Definition(
      'normal_cards_25',
      AchievementCategory.cards,
      AchievementMetric.persistedNormalCards,
      25,
      400,
      9,
      AchievementTier.gold,
      'album',
    ),
    _Definition(
      'normal_cards_50',
      AchievementCategory.cards,
      AchievementMetric.persistedNormalCards,
      50,
      750,
      10,
      AchievementTier.platinum,
      'crown_card',
    ),
    _Definition(
      'first_uncommon',
      AchievementCategory.rarity,
      AchievementMetric.uncommonDiscoveries,
      1,
      75,
      11,
      AchievementTier.bronze,
      'sparkle',
    ),
    _Definition(
      'first_rare',
      AchievementCategory.rarity,
      AchievementMetric.rareDiscoveries,
      1,
      150,
      12,
      AchievementTier.silver,
      'diamond',
    ),
    _Definition(
      'first_epic',
      AchievementCategory.rarity,
      AchievementMetric.epicDiscoveries,
      1,
      300,
      13,
      AchievementTier.gold,
      'magic',
    ),
    _Definition(
      'first_legendary',
      AchievementCategory.rarity,
      AchievementMetric.legendaryDiscoveries,
      1,
      600,
      14,
      AchievementTier.platinum,
      'legendary',
    ),
    _Definition(
      'first_geolocated_discovery',
      AchievementCategory.exploration,
      AchievementMetric.geolocatedDiscoveries,
      1,
      75,
      15,
      AchievementTier.bronze,
      'pin',
    ),
    _Definition(
      'geolocated_discoveries_5',
      AchievementCategory.exploration,
      AchievementMetric.geolocatedDiscoveries,
      5,
      200,
      16,
      AchievementTier.silver,
      'city',
    ),
    _Definition(
      'geolocated_discoveries_20',
      AchievementCategory.exploration,
      AchievementMetric.geolocatedDiscoveries,
      20,
      500,
      17,
      AchievementTier.gold,
      'globe',
    ),
    _Definition(
      'first_daily_mission',
      AchievementCategory.missions,
      AchievementMetric.claimedDailyMissions,
      1,
      50,
      18,
      AchievementTier.bronze,
      'check',
    ),
    _Definition(
      'daily_missions_10',
      AchievementCategory.missions,
      AchievementMetric.claimedDailyMissions,
      10,
      200,
      19,
      AchievementTier.silver,
      'calendar',
    ),
    _Definition(
      'daily_missions_30',
      AchievementCategory.missions,
      AchievementMetric.claimedDailyMissions,
      30,
      500,
      20,
      AchievementTier.gold,
      'streak',
    ),
    _Definition(
      'first_event_card',
      AchievementCategory.events,
      AchievementMetric.persistedEventCards,
      1,
      100,
      21,
      AchievementTier.bronze,
      'event',
      eventKey: halloweenEventKey,
    ),
    _Definition(
      'halloween_free_collection',
      AchievementCategory.events,
      AchievementMetric.halloweenFreeVariants,
      3,
      300,
      22,
      AchievementTier.gold,
      'pumpkin',
      eventKey: halloweenEventKey,
    ),
    _Definition(
      'halloween_premium_collection',
      AchievementCategory.events,
      AchievementMetric.halloweenPremiumVariants,
      3,
      500,
      23,
      AchievementTier.platinum,
      'witch',
      eventKey: halloweenEventKey,
    ),
    _Definition(
      'level_5',
      AchievementCategory.progression,
      AchievementMetric.playerLevel,
      5,
      100,
      24,
      AchievementTier.bronze,
      'level',
    ),
    _Definition(
      'level_10',
      AchievementCategory.progression,
      AchievementMetric.playerLevel,
      10,
      250,
      25,
      AchievementTier.silver,
      'level',
    ),
    _Definition(
      'level_25',
      AchievementCategory.progression,
      AchievementMetric.playerLevel,
      25,
      500,
      26,
      AchievementTier.gold,
      'level',
    ),
    _Definition(
      'level_50',
      AchievementCategory.progression,
      AchievementMetric.playerLevel,
      50,
      1000,
      27,
      AchievementTier.platinum,
      'level',
    ),
  ];
}

class _Definition extends AchievementDefinition {
  // A compact private constructor keeps all V1 thresholds in one table.
  // ignore: use_super_parameters
  const _Definition(
    String id,
    AchievementCategory category,
    AchievementMetric metric,
    int target,
    int reward,
    int order,
    AchievementTier tier,
    String icon, {
    String? eventKey,
  }) : super(
         achievementId: id,
         category: category,
         metric: metric,
         localizedTitleKey: 'achievement.$id.title',
         localizedDescriptionKey: 'achievement.$id.description',
         localizedLockedHintKey: 'achievement.$id.hint',
         iconKey: icon,
         targetValue: target,
         rewardXp: reward,
         sortOrder: order,
         tier: tier,
         isEventSpecific: eventKey != null,
         eventKey: eventKey,
       );
}
