#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/opt/homebrew/share/flutter"
export "FLUTTER_APPLICATION_PATH=/Users/giuppy/Downloads/catdex-main"
export "FLUTTER_FRAMEWORK_SWIFT_PACKAGE_PATH=/Users/giuppy/Downloads/catdex-main/ios/Flutter/ephemeral/Packages/.packages/FlutterFramework"
export "COCOAPODS_PARALLEL_CODE_SIGN=true"
export "FLUTTER_TARGET=/Users/giuppy/Downloads/catdex-main/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "FLUTTER_BUILD_NAME=0.1.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=U1VQQUJBU0VfVVJMPWh0dHBzOi8veW1kd25vaGNuamNpamdicW5yaXkuc3VwYWJhc2UuY28=,U1VQQUJBU0VfQU5PTl9LRVk9c2JfcHVibGlzaGFibGVfbWx2OEZSS1lGTTZhc095WU13NjRhZ180TmZFSXRSSw==,Q0FSRF9HRU5FUkFUSU9OX0FQSV9VUkw9aHR0cDovL2xvY2FsaG9zdDozMDAwL2FwaS9nZW5lcmF0ZS1jYXJk,RkxVVFRFUl9WRVJTSU9OPTMuNDQuNA==,RkxVVFRFUl9DSEFOTkVMPXN0YWJsZQ==,RkxVVFRFUl9HSVRfVVJMPWh0dHBzOi8vZ2l0aHViLmNvbS9mbHV0dGVyL2ZsdXR0ZXIuZ2l0,RkxVVFRFUl9GUkFNRVdPUktfUkVWSVNJT049YWQ3MGVjNDYxNw==,RkxVVFRFUl9FTkdJTkVfUkVWSVNJT049YTEwZDhhYzM4ZA==,RkxVVFRFUl9EQVJUX1ZFUlNJT049My4xMi4y"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=/Users/giuppy/Downloads/catdex-main/.dart_tool/package_config.json"
